spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true

  cache:
    type: redis



jwt:
  tokenHeader: auth-token #JWT存储的请求头
  secure: ZAQ!xsw2
  expire: 300000
  tokenHead: Bearer #JWT负载中拿到开头
server:
  port: 8080
