spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true

jwt:
  header: "auth-token"
  secure: ZAQ!xsw2
  expire: 300000
server:
  port: 8080
