spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    password: lts950410
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true # 懒加载解决问题
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql

  rabbitmq:
    host: localhost
    username: guest
    password: '!QAZ2wsx'
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    healthcheck:
      enabled: true
  instance:
    # 服务续约（秒）
    # 服务续约间隔时间
    lease-renewal-interval-in-seconds: 1
    # 服务失效时间
    lease-expiration-duration-in-seconds: 1
    # 不使用主机名来定义注册中心的地址，而使用IP地址的形式，如果设置了
    #eureka.instance.ip-address 属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 状态页面的URL，绝对路径
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/info
    # 健康检查页面的URL，绝对路径
    health-check-url: http://${eureka.instance.ip-address}:${server.port}/health

# 将git上的配置放到本地，防止连不上git
jwt:
  tokenHeader: auth-token #JWT存储的请求头
  secure: ZAQ!xsw2
  expire: 300000
  tokenHead: Bearer #JWT负载中拿到开头
secure:
  ignore:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /register
      - /login
      - /api/resource

role:
  name: regular
  code: regular
  description: 普通用户

authority:
  mybatisAuthoritySettings:
    -
      authorityCode: TEST_AUTHORITY
      columnConstraints:
        -
          columnName: state
          operation: EQUAL
          constraints: "'state3'"