server:
  port: 8091

spring:
  profiles:
    active: dev
  application:
    name: blog-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cestdestiny/config-repo.git
          search-paths: config-dev